# Generated by Django 4.2.4 on 2023-10-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college_admin',
            options={'verbose_name_plural': 'College_Admins'},
        ),
        migrations.AlterField(
            model_name='college_admin',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
