from django.db import models

class Data_2023(models.Model):
  Institute_id = models.CharField(unique=True, max_length=100)
  Name = models.CharField(max_length=100)
  City = models.CharField(max_length=100)
  State = models.CharField(max_length=100)
  TLR = models.CharField(max_length=100)
  RPC = models.CharField(max_length=100)
  GO = models.CharField(max_length=100)
  OI = models.CharField(max_length=100)
  PR = models.CharField(max_length=100)
  Score = models.CharField(max_length=100)
  Rank = models.CharField(max_length=100)

class Data_2022(models.Model):
  Institute_id = models.CharField(unique=True, max_length=100)
  Name = models.CharField(max_length=100)
  City = models.CharField(max_length=100)
  State = models.CharField(max_length=100)
  TLR = models.CharField(max_length=100)
  RPC = models.CharField(max_length=100)
  GO = models.CharField(max_length=100)
  OI = models.CharField(max_length=100)
  PR = models.CharField(max_length=100)
  Score = models.CharField(max_length=100)
  Rank = models.CharField(max_length=100)

class Data_2021(models.Model):
  Institute_id = models.CharField(unique=True, max_length=100)
  Name = models.CharField(max_length=100)
  City = models.CharField(max_length=100)
  State = models.CharField(max_length=100)
  TLR = models.CharField(max_length=100)
  RPC = models.CharField(max_length=100)
  GO = models.CharField(max_length=100)
  OI = models.CharField(max_length=100)
  PR = models.CharField(max_length=100)
  Score = models.CharField(max_length=100)
  Rank = models.CharField(max_length=100)

class Data_2020(models.Model):
  Institute_id = models.CharField(unique=True, max_length=100)
  Name = models.CharField(max_length=100)
  City = models.CharField(max_length=100)
  State = models.CharField(max_length=100)
  TLR = models.CharField(max_length=100)
  RPC = models.CharField(max_length=100)
  GO = models.CharField(max_length=100)
  OI = models.CharField(max_length=100)
  PR = models.CharField(max_length=100)
  Score = models.CharField(max_length=100)
  Rank = models.CharField(max_length=100)

class Data_2019(models.Model):
  Institute_id = models.CharField(unique=True, max_length=100)
  Name = models.CharField(max_length=100)
  City = models.CharField(max_length=100)
  State = models.CharField(max_length=100)
  TLR = models.CharField(max_length=100)
  RPC = models.CharField(max_length=100)
  GO = models.CharField(max_length=100)
  OI = models.CharField(max_length=100)
  PR = models.CharField(max_length=100)
  Score = models.CharField(max_length=100)
  Rank = models.CharField(max_length=100)

class Data_2018(models.Model):
  Institute_id = models.CharField(unique=True, max_length=100)
  Name = models.CharField(max_length=100)
  City = models.CharField(max_length=100)
  State = models.CharField(max_length=100)
  TLR = models.CharField(max_length=100)
  RPC = models.CharField(max_length=100)
  GO = models.CharField(max_length=100)
  OI = models.CharField(max_length=100)
  PR = models.CharField(max_length=100)
  Score = models.CharField(max_length=100)
  Rank = models.CharField(max_length=100)

class Data_2017(models.Model):
  Institute_id = models.CharField(unique=True, max_length=100)
  Name = models.CharField(max_length=100)
  City = models.CharField(max_length=100)
  State = models.CharField(max_length=100)
  TLR = models.CharField(max_length=100)
  RPC = models.CharField(max_length=100)
  GO = models.CharField(max_length=100)
  OI = models.CharField(max_length=100)
  PR = models.CharField(max_length=100)
  Score = models.CharField(max_length=100)
  Rank = models.CharField(max_length=100)

class Data_2016(models.Model):
  Institute_id = models.CharField(unique=True, max_length=100)
  Name = models.CharField(max_length=100)
  City = models.CharField(max_length=100)
  State = models.CharField(max_length=100)
  TLR = models.CharField(max_length=100)
  RPC = models.CharField(max_length=100)
  GO = models.CharField(max_length=100)
  OI = models.CharField(max_length=100)
  PR = models.CharField(max_length=100)
  Score = models.CharField(max_length=100)
  Rank = models.CharField(max_length=100)